# fly.toml app configuration file generated for telegramtestbot on 2023-08-29T21:38:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegramtestbot"
primary_region = "waw"
